### ISSUE TITLE
Add configurable contact email near "compacted/delete" strategy field.

### ISSUE THREAD

**Issue by SergKam** [zalando-incubator/nakadi-ui#13]
Add configurable contact email near compacted delete strategy field.
It should be specific email address instead of just `check the legal department of your organization`

![screenshot 42](https://user-images.githubusercontent.com/3240529/44208581-06a24e80-a161-11e8-8177-54fd4cbb7064.png)

**Comment by himanshugahlaut** [comment]
Log compacted event types MUST NOT contain personally identifiable information in accordance to GDPR. If you plan to store personal user data permanently in Log compacted event types, then please get in touch with <email-address> to get a custom GDPR compliant solution built for your use case.

**Comment by himanshugahlaut** [comment]
i would suggest nakadi-gdpr@zalando.de to be the email address. If you think this email address is fine then carine can get it from tech stop.

**Comment by SergKam** [comment]
In the end, it is just a support request, so we will use just a standard SUPPORT_URL

**Comment by SergKam** [comment]
![screenshot 48](https://user-images.githubusercontent.com/3240529/44339240-f18b2f80-a480-11e8-9d96-ab6e7bd2f076.png)

**Comment by SergKam** [comment]
Done
