### ISSUE TITLE
Add an ability to delete added security rule for the event

### ISSUE THREAD

**Issue by iCubeDm** [zalando-incubator/nakadi-ui#17]
**As an** event admin
**I want to** be able to manage my security configuration
**So that** it is possible to delete already added rules (e.g. I want to delete a user/service from the read list)

**Comment by SergKam** [comment]
But you can do this already just update ET and remove all access privileges from any entry (read, write, admin).
Entries with no privileges will be deleted automatically.
We can only add "delete" button if it not obvious.

**Comment by iCubeDm** [comment]
Ah so!!! That is definitely not obvious. And yeah, it would be nice to have a "delete" button.

**Comment by SergKam** [comment]
Done
