### ISSUE TITLE
Check required fields in update event type form

### ISSUE THREAD

**Issue by a1exsh** [zalando-incubator/nakadi-ui#26]
Currently the form for updating an event type would happily allow you to omit some fields which are marked as required in the form itself, e.g. "Owning application" and "Audience".  Then the API responds with `400 Bad Request` which is sometimes not really straightforward to parse.

In case of omitting the owning application, no error occurs at all.  So this is contradictory to the marking of the field as required.

Preferably, the HTML form in UI would highlight the required and missing fields with red color when the user tries to submit it, avoiding the API call in the first place.

**Comment by SergKam** [comment]
Fixed
